cad:
- bltouch_v8.step
description: Drop in replacement of the stock probe to a BLTouch
images:
- pic_2.jpg
- pic_1.jpg
mod_version: 1
printer_compatibility:
- V2.1
stl:
- bltouch_v8.stl
title: BlTouch Mount
