cad: 
- CAD/DuetZero.step
description: Pi Zero mount over a Duet2 for space saving
images:
- example.jpg
mod_version: 1
printer_compatibility:
- V0.2
- V1.8
- V2.4
stl:
- DuetZero.stl
title: DuetZero
