title: V0 Modesty Mesh
description: customizable mesh panels to hide your wiring mess
printer_compatibility: 
 - V0
images: 
 - Images/parts.png
 - Images/render.png
 - Images/sliced.png
cad: 
 - CAD/V0_Modesty_Mesh.step
discord_username: mapleleafmakers
mod_version: 1

