cad:
- CAD/v2.4_z_drive_motor_tensioner_mod.step
- CAD/[a]_2.4_base_plate_a_mod_x2.step
- CAD/[a]_2.4_base_plate_b_mod_x2.step
description: Braced motor tensioner for z drive
images:
- z_drive_mod.png
mod_version: 2
printer_compatibility:
- V2.4r2
stl:
- STLs/z_motor_mount_a_mod_x2.stl
- STLs/z_motor_mount_b_mod_x2.stl
- STLs/[a]_2.4_base_plate_a_mod_x2.stl
- STLs/[a]_2.4_base_plate_b_mod_x2.stl
- STLs/[a]_base_plate_a_mod_x2.stl
- STLs/[a]_base_plate_b_mod_x2.stl
- STLs/Skirts/250/250_front_rear_skirt_a_x2mod.stl
- STLs/Skirts/250/250_front_rear_skirt_b_x2mod.stl
- STLs/Skirts/300/300_front_rear_skirt_a_x2mod.stl
- STLs/Skirts/300/300_front_rear_skirt_b_x2mod.stl
- STLs/Skirts/350/350_front_rear_skirt_a_x2_mod.stl
- STLs/Skirts/350/350_front_rear_skirt_b_x2mod.stl
title: V2.4 Z Drive Motor Tensioner Mod
