cad: []
description: Moves power switch to right front skirt on the Trident
images:
- Images/Front_View.png
- Images/Filter_Front_View.png
- Images/ISO_View.png
- Images/Filter_ISO_View.png
mod_version: 1
printer_compatibility:
- VT
stl:
- Filtered_Main_Skirt.stl
- Side_Skirt_A_Switch.stl
title: Trident Right Skirt Switch
