cad: 
- CAD/HOYMK_SSR_Mount_B.step
- CAD/HOYMK_SSR_Mount_A.step
description: Mount for Chinese HOYMK SSR
images: []
mod_version: 1
printer_compatibility:
- V0.2
stl:
- Alternative_A.stl
- Alternative_B_1.stl
- Alternative_B_2.stl
title: HOYMK SSR Mount
