cad: 
- CAD/350_Deck_Panel.dxf  
- CAD/Bed_Hinge.f3z
description: A way of reaching electronics from the top by having a "car hood" style
  hinge for the heatbed, and rotated electronics mounts.
images:
- Pictures/result.gif
- Pictures/piston.jpg
mod_version: 1
printer_compatibility:
- V2.4
stl:
- STLs/Deck_Panel_Holder.stl
- STLs/Din_Rail_Mount.stl
- STLs/Extrusion_Spacer.stl
- STLs/Front.stl
- STLs/Handle.stl
title: Car Hood Style Bed Hinge
