---
title: Umbilical Collar
description: An adjustable umbilical collar for the stock motor panel on the V0
mod_version: 1
discord_username: mapleleafmakers
cad:
- CAD/umbilical_collar.step
images:
- Images/V0_Umbilical_Collar.gif
- Images/assembly.png
- Images/motor_panel.png
printer_compatibility:
- V0
