cad:
- mains_plug_panel-parametric.f3d
description: Scalable mains plug panel with small modifications
images: []
mod_version: 1
printer_compatibility:
- V1.6
- V2.1
- V2.2
stl: []
title: Mains Plug Panel Parametric
