---
title: Modesty Mesh
description: Customizable mesh inserts to hide your messy electronics compartment.
mod_version: 1
discord_username: mapleleafmakers
cad:
- CAD/V0_Modesty_Mesh.step
images:
- Images/render.png
- Images/parts.png
- Images/sliced.png
printer_compatibility:
- V0
