cad:
- CAD/Tool_free_tensioner.STEP
description: Tool-free tensioner for Z-Axis
images:
- Images/Tool_free_tensioner_1.png
- Images/Tool_free_tensioner_2.png
mod_version: 1
printer_compatibility:
- V2.4
stl:
- STL/bracket.stl
- STL/tensioner.stl
- STL/wheel.stl
title: Tool_free_tensioner
