; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v3.1.3 on Sun Jul 12 2020 20:53:52 GMT+0200 (Central European Summer Time)
M98 P"/macros/Home/z_current_low.g"
G91               	; relative positioning
G1 H2 Z10 F6000    	; lift Z relative to current position
G90				  	; absolute positioning
M98 P"/macros/Home/move_over_microswitch.g"		; move above the endstop switch
G30 K1 Z-99999
M98 P"/macros/Home/z_current_high.g"
