; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.1.3 on Sun Jul 12 2020 20:53:53 GMT+0200 (Central European Summer Time)

M98 P"0:/macros/Print/Print end"
