cad: 
- CAD/Easy_Access_Rear_Panels_v0_Bottom.step
- CAD/Easy_Access_Rear_Panels_v0_Top.step
description: New rear panels designed to expose the extruder for easy filament swapping
images:
- example.jpg
mod_version: 1
printer_compatibility:
- V0.2
stl:
- Bottom.stl
- Top.stl
title: Easy Access Rear Panels
