cad: 
- CAD/Flat_Skirts_in.step
- CAD/Flat_Skirts_Mid.step
description: Flat V2.4 Skirts so a panel without cutouts can be used
images: []
mod_version: 1
printer_compatibility:
- V2.4
stl:
- Filtered_In.stl
- Middle_Side_Skirt.stl
title: Flat V2.4 Skirts
