---
blank_issues_enabled: false
contact_links:
  - name: I want to learn about the submission rules for this repository
    url: https://github.com/VoronDesign/VoronUsers/wiki/Mod-Submission-Rules
    about: You can find the submission rules in the wiki of this repository
  - name: I'm looking for general discussions about VoronUser mods
    url: https://discord.com/channels/460117602945990666/635687829254701107
    about: Check out the `#voronuser_mods` channel on the VoronDesign discord
  - name: I have an issue with a VoronDesign printer
    url: https://discord.gg/voron
    about: Please use the help channels for the individual printers on the VoronDesign discord
  - name: I have an issue with a VoronDesign printer and don't want to use Discord
    url: https://forum.vorondesign.com
    about: Check out the VoronDesign forums
  - name: I want to request a mod or a feature for a particular mod
    url: https://discord.com/channels/460117602945990666/635687829254701107
    about: Please join the VoronDesign discord and ask about your request in the `#voronuser_mods` channel
