cad: 
- CAD/V0_Picam.step
description: A Raspberry Pi Camera Mount For V0
images:
- example.jpg
mod_version: 1
printer_compatibility:
- V0.2
stl:
- Ball.stl
- Cam_A.STL
- Cam_B.STL
title: V0 PiCam Mount
