title: In Situ Linear Carriage Block Lubrication
# A short description of your mod. Try to describe your mod with 1-2 short sentences
description: A modification that allow lubrication of the linear reals while fully assembled.
# Mod version: Set this to 1 when you are submitting a new mod. When you make changes to your mod, you may increment this number
mod_version: 1
# You may add your discord username here so people can contact you about your mod
discord_username: Jan_P
# The CAD files for your mod. Please provide them as a list.
# Note that each mod must include at least one CAD file.
cad:
- ./CAD/greasing_concept.step
# The image files provided with your mod. These may be instructions you use in your README.md file, or other additional pictures.
# **Note that the first image specified here will be used as cover image on mods.vorondesign.com**
# All paths are relative to this .metadata.yml file.
images:
- ./IMG/after_install.png
- ./IMG/attach_syringe.png
- ./IMG/in_situ_drilling_operation.png
- ./IMG/in_situ_regreasing.png
- ./IMG/materials.png
- ./IMG/ventilated_screws.png
- ./IMG/voron-regreasing-concept.png
- ./IMG/y_axis_lubrication_screw.png
- ./IMG/z_axis_lubrication_screw.png
# Printer compatibility. Please specify all compatible printers as a list. The following values are accepted:
# "V0", "V0.1", "V0.2", "V0.2r1", "V1", "V1.6", "V1.8", "V1.8r1",  "V2", "V2.1", "V2.2", "V2.4", "V2.4r1", "V2.4r2", "VSW", "VT", "VTr1", "VL"
# Please only specify printers that you have either tested your mod on yourself, or that someone else has tested for you. If you are unsure whether your
# mod is compatible with a certain printer, don't list it here!
printer_compatibility:
- V2.4r2
