cad:
- cad/slenderfan.step
description: Lighter, quieter, smaller Afterburner
images:
- images/printer.png
- images/render.png
- images/render_open.png
mod_version: 1
printer_compatibility:
- V2.4
title: Slenderfan for Afterburner
