M48
; DRILL file {KiCad (6.0.6)} date Fri Aug  5 00:51:17 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-05T00:51:17+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X2.8937Y-4.2028
X3.563Y-4.2047
X4.5211Y-3.3331
X4.5211Y-4.1087
T0
M30
