---
# The title of your mod. Choose a short and descriptive name
title: Stealthburner Phaetus Dragon UHF and Phaetus Dragon UHF mini
# A short description of your mod. Try to describe your mod with 1-2 short sentences
description: This mod adds a tool cartridge for the Phaetus Dragon UHF and Phaetus Dragon UHF mini hotend
# Mod version: Set this to 1 when you are submitting a new mod. When you make changes to your mod, you may increment this number
mod_version: 1
# You may add your discord username here so people can contact you about your mod
discord_username: emjay276
# The CAD files for your mod. Please provide them as a list.
# Note that each mod must include at least one CAD file.
cad:
- CAD/Stealthburner_Printhead_Dragon_UHF.stp
- CAD/Stealthburner_Printhead_Dragon_UHF_mini.stp
# The image files provided with your mod. These may be instructions you use in your README.md file, or other additional pictures.
# **Note that the first image specified here will be used as cover image on mods.vorondesign.com**
# All paths are relative to this .metadata.yml file.
images:
- images/back.png
- images/back_uhf.png
- images/back_uhf_mini.png
- images/cable_channel.png
- images/cross_section.png
- images/front.jpg
- images/front_uhf.png
- images/front_uhf_mini.png
- images/hotend_installation.jpg
# Printer compatibility. Please specify all compatible printers as a list. The following values are accepted:
# "V0", "V0.1", "V0.2", "V0.2r1", "V1", "V1.6", "V1.8", "V1.8r1",  "V2", "V2.1", "V2.2", "V2.4", "V2.4r1", "V2.4r2", "VSW", "VT", "VTr1", "VL"
# Please only specify printers that you have either tested your mod on yourself, or that someone else has tested for you. If you are unsure whether your
# mod is compatible with a certain printer, don't list it here!
printer_compatibility:
- VT
- V2.4