cad: 
- CAD/Relay_DIN_Mount.step
description: A simple DIN rail mount for the 4 channel relay board for Raspberry Pi
images: []
mod_version: 1
printer_compatibility:
- V1.8
- V2.4
stl:
- Relay.stl
title: DIN Mount Pi 4x Relay Board
