cad:
- CAD/V0.2_Handle.step
description: Add handles to the extrusion tophat
images:
- Images/Handle_1.jpeg
- Images/Handle_2.png
- Images/Handle_3.png
- Images/2.png
- Images/3.png
- Images/1.png
mod_version: 1
printer_compatibility:
- V0.2
title: V0.2 Handles
