M48
; DRILL file {KiCad (6.0.6)} date Fri Aug 12 20:52:15 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-12T20:52:15+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X2.5276Y-2.1909
X2.9764Y-2.1909
X3.4252Y-2.1909
X4.1071Y-2.5654
X4.1071Y-3.3409
T0
M30
