cad:
- CAD/bowden_guide.f3d
- CAD/left_front.f3d
- CAD/right_front.f3d
- CAD/left_rear.f3d
- CAD/right_rear.f3d
description: Taller Z Mod
images:
- IMAGES/tall_z_rear.PNG
- IMAGES/picture.jpg
- IMAGES/tall_z_front.PNG
mod_version: 1
printer_compatibility:
- VSW
title: Ender 3 Switchwire Taller Z Mod
