; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Fri Apr 10 2020 10:47:41 GMT+0200 (Mitteleuropäische Sommerzeit)

