cad: 
- CAD/V0_M4_Mod.step
description: Mod to mount a M4 extruder to a Voron 0 where pocketwatch extruder mounts
images:
- example.jpg
mod_version: 1
printer_compatibility:
- V0.2
stl:
- End_Plate.stl
- Motor_Plate.stl
title: Mobius 4 (M4) V0 Mod
