cad:
- CAD/v2.4_z_drive_motor_tensioner_mod.step
- CAD/[a]_2.4_base_plate_a_mod_x2.step
- CAD/[a]_2.4_base_plate_b_mod_x2.step
description: Braced motor tensioner for z drive
images:
- z_drive_mod.png
mod_version: 1
printer_compatibility:
- V2.4
title: V2.4 Z Drive Motor Tensioner Mod
