cad: []
description: Simple bracket to mount an LED strip
images:
- Images/LED_Holder_Picture.jpg
- Images/LED_Holder_ISO.png
- Images/LED_Strip_Example.jpg
- Images/LED_Holder_Side_View.png
mod_version: 1
printer_compatibility:
- VT
- V2.4
stl:
- LED_Holder_340mm.stl
title: LED Strip Holder
