cad: 
- CAD/Duct_Mount.step
description: 100mm/4" ducting mount for ventilation. Also supports umbilical cord
  and has 3 orientations for bowden adapter.
images:
- example.jpg
- example2.jpg
mod_version: 1
printer_compatibility:
- V2.4
stl:
- Body2.stl
- Body3.stl
- Body4.stl
title: Duct Mount
