---
# The title of your mod. Choose a short and descriptive name
title: Ballpoint pen spring DIN clips
# A short description of your mod. Try to describe your mod with 1-2 short sentences
description: Assortment of mechanical DIN clips using common ballpoint pen springs.
# Mod version: Set this to 1 when you are submitting a new mod. When you make changes to your mod, you may increment this number
mod_version: 1
# You may add your discord username here so people can contact you about your mod
discord_username: aeresov
# The CAD files for your mod. Please provide them as a list.
# Note that each mod must include at least one CAD file.
cad:
- CAD/shuttle.step
- CAD/button.step
- CAD/carriage_no_mounts.step
# The image files provided with your mod. These may be instructions you use in your README.md file, or other additional pictures.
# **Note that the first image specified here will be used as cover image on mods.vorondesign.com**
# All paths are relative to this .metadata.yml file.
images:
- Images/clip_on.jpg
- Images/clip_off.jpg
- Images/spring_position.jpg
- Images/bracket_on.jpg
# List all STL files
stl:
- STL/shuttle.stl
- STL/button.stl
- STL/carriage_PCB_tap.stl
- STL/carriage_PCB_inserts.stl
- STL/carriage_RS25.stl
- STL/carriage_LRS200.stl
- STL/carriage_UHP200_inserts.stl
- STL/carriage_UHP200_screw.stl
- STL/carriage_UHP350_inserts.stl
- STL/carriage_UHP350_screw.stl
- STL/carriage_UHP500_inserts.stl
- STL/carriage_UHP500_screw.stl
# Printer compatibility. Please specify all compatible printers as a list. The following values are accepted:
# "V0", "V0.1", "V0.2", "V0.2r1", "V1", "V1.6", "V1.8", "V1.8r1",  "V2", "V2.1", "V2.2", "V2.4", "V2.4r1", "V2.4r2", "VSW", "VT", "VTr1", "VL"
# Please only specify printers that you have either tested your mod on yourself, or that someone else has tested for you. If you are unsure whether your
# mod is compatible with a certain printer, don't list it here!
printer_compatibility:
- VT
- V2.4r2
