cad:
- PiPlate_v16.f3d
- PiPlate_v16.step
description: PiPlate - Raspberry Pi3,4 mounting plate and Skirt Mod for V2.4/Trident
images:
- PiPlate.jpg
- PiPlate2.jpg
mod_version: 1
printer_compatibility:
- V2.4
- VT
title: PiPlate
